name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31
      - run: nix flake check
      - shell: "nix develop -c bash -e {0}"
        run: gleam deps download
      - shell: "nix develop -c bash -e {0}"
        run: gleam build --warnings-as-errors
      - shell: "nix develop -c bash -e {0}"
        run: gleam test --target erlang
      - shell: "nix develop -c bash -e {0}"
        run: gleam test --target javascript
